### ISSUE TITLE
Come on, can someone finally make a working API that is still available on the internet

### ISSUE THREAD

**Issue by BlackOutBG** [jagrosh/DiscordIPC#10]
This is the third Java API that I try using and it is not even available on jCentral, as written on the README.MD.

**Comment by jagrosh** [comment]
It is most definitely on jcenter: http://jcenter.bintray.com/com/jagrosh/DiscordIPC/

This is likely an error on your part; double-check that you're using the correct repository, artifact name, and version number. The current latest version is `0.4`

Also, please refrain from using profanity in your issues, and please don't complain about other libraries here.
