### ISSUE TITLE
README example is broken in Ubuntu

### ISSUE THREAD

**Issue by MrPowerGamerBR** [jagrosh/DiscordIPC#16]
```kotlin
object Main {
    @JvmStatic
    fun main(args: Array<String>) {
        val client = IPCClient(384465696496549888L)
        client.setListener(object : IPCListener {
            override fun onReady(client: IPCClient?) {
                val builder = RichPresence.Builder()
                builder.setState("West of House")
                    .setDetails("Frustration level: Over 9000")
                    .setStartTimestamp(OffsetDateTime.now())
                    .setLargeImage("canary-large", "Discord Canary")
                    .setSmallImage("ptb-small", "Discord PTB")
                    .setParty("party1234", 1, 6)
                    .setMatchSecret("xyzzy")
                    .setJoinSecret("join")
                    .setSpectateSecret("look")
                client!!.sendRichPresence(builder.build())
            }
        })
        client.connect()
    }
}
```

```
Exception in thread "main" java.lang.RuntimeException: java.net.SocketException: Socket file not found: /run/user/1000/snap.intellij-idea-community/discord-ipc-0
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:167)
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
	at com.mrpowergamerbr.powerrp.Main.main(Main.kt:34)
Caused by: java.net.SocketException: Socket file not found: /run/user/1000/snap.intellij-idea-community/discord-ipc-0
	at org.newsclub.net.unix.AFUNIXSocketImpl.validateSocketFile(AFUNIXSocketImpl.java:164)
	at org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:154)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:138)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:117)
	at com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:46)
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:163)
	... 3 more
```

I'm running the code directly from IDEA, maybe that's why it isn't working? Discord's IPC socket is in `./run/user/1000/discord-ipc-0` on my system

**Comment by MrPowerGamerBR** [comment]
Just for fun I created a symlink `ln -s /run/user/1000/discord-ipc-0 /run/user/1000/snap.intellij-idea-community/discord-ipc-0`, and...

![image](https://user-images.githubusercontent.com/9496359/50692028-b2b5da80-1019-11e9-8bc4-1063ebc49216.png)

**Comment by Shengaero** [comment]
If it's not too much to ask, could you add this line to the program near the start and report back what it gives you?
```kotlin
prinln(System.getProperty("java.io.tmpdir"))```

**Comment by MrPowerGamerBR** [comment]
@Shengaero `/tmp`

**Comment by MrPowerGamerBR** [comment]
```
XDG_RUNTIME_DIR is /run/user/1000/snap.intellij-idea-community
/run/user/1000/snap.intellij-idea-community/discord-ipc-0
```

**Comment by Shengaero** [comment]
It seems like it's an [ubuntu related thing](https://askubuntu.com/questions/872792/what-is-xdg-runtime-dir).

**Comment by MrPowerGamerBR** [comment]
It actually seems that [snap](https://snapcraft.io/) sets the `XDG_RUNTIME_DIR` automatically for applications installed via snap. (and the `tmp` & others variables aren't set automatically)

Compiling the rich presence and running via the terminal works fine, so it is just an issue if you are running via IDEA itself.

Maybe adding an option to override the socket path when using `client.connect()`? I think `XDG_RUNTIME_DIR` is used *if you install Discord via snap* (in my case: I installed it directly from Discord's website) and you are running the rich presence client via the terminal, but I'm not sure.

**Comment by Shengaero** [comment]
you can probably just set that system property from earlier to the new temp dir

**Comment by MrPowerGamerBR** [comment]
Installing IDEA via Jetbrains Toolbox fixed the issue.

Maybe adding a small note in the README that, if IDEA is installed via snap/Ubuntu App Store, it won't work/will require workarounds?

**Comment by Shengaero** [comment]
This seems very edge case and we won't be putting something in the readme, we will simply refer anyone having trouble to this issue.
Closing this now, thanks for help debugging!
