### ISSUE TITLE
JCenter completely shutting down soon

### ISSUE THREAD

**Issue by thegu5** [jagrosh/DiscordIPC#21]
JCenter completely shuts down on feb 1st, which is 20 days from now. Are there any plans to use gradle? A pr was made a while ago to support it( #9 ).

@jagrosh

**Comment by jagrosh** [comment]
JCenter is not shutting down completely. JCenter will no longer be used for any new releases (which will use either jitpack or maven central), but JCenter for existing versions will continue to work "indefinitely."

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

Therefore, there is no need to switch away from JCenter until a new release is made.

---

> Are there any plans to use gradle?

Probably not, I prefer and have experience in maven.
