### ISSUE TITLE
Not sending presence when no party set.

### ISSUE THREAD

**Issue by MaxiMiniJaniJos** [jagrosh/DiscordIPC#6]
When building and you do not set party the presence won't show up on discord at all.

**Comment by jagrosh** [comment]
Can you print out the message from the callback when not setting the party?

**Comment by MaxiMiniJaniJos** [comment]
using the code
client.sendRichPresence(builder.build(), new Callback((Consumer<String>) System.out::println));
I receive this:
child "activity" fails because [child "party" fails because [child "size" fails because ["size" at position 0 fails because ["0" must be larger than or equal to 1]]]]

**Comment by TheMonitorLizard** [comment]
We need to come up with a good way of forcing people to set the minimum requirements to successfully send a rich presence methinks.

**Comment by jagrosh** [comment]
Party isn't required, I know what's going wrong here and I'll have a fix for it in the next release

**Comment by MaxiMiniJaniJos** [comment]
May I ask what is going wrong? And any date for next release?

**Comment by jagrosh** [comment]
This should be fixed as of release 0.3 (just released)

**Comment by MaxiMiniJaniJos** [comment]
I've tested it and it's fixed thanks!
